### ISSUE TITLE
Dragon Age: Inquisition not launching with EA Desktop

### ISSUE THREAD

**Issue by yeke2000** [Dyvinia/FrostyFix#10]
![frostyfix](https://user-images.githubusercontent.com/45556197/153193355-963a5a6e-c8da-4257-b9a3-882322457383.JPG)

When I try to launch Dragon Age: Origins with "EA Desktop" or "Global" as platform EA Desktop starts and nothing further happens. When I then try to launch Dragon Age from EA Desktop all that's happening is EA Desktop restarting.

**Comment by yeke2000** [comment]
Just realized there seems to be a problem with the profiles. FrostyModManager doesn't create profile folders under Dragon Age Inquisition/ModData for me. I created a folder "Default" (the profile I use in FrostyModManager) under /ModData and moved the other folders under /ModData inside it. Now Dragon Age launches but mods still are not working.

**Comment by Dyvinia** [comment]
Use the frosty alpha

**Comment by yeke2000** [comment]
Unfortunately mods are not working with frosty alpha 5 either but I guess it's not a problem with FrostyFix then.
