### ISSUE TITLE
Not launching the game

### ISSUE THREAD

**Issue by Ooprec** [Dyvinia/FrostyFix#11]
I'm attempting to launch Star Wars Battlefront II using this program, but the game won't start if I click the button (Btw I got SWBF2 free on the epic games store, so i know modding on that is a bit scuffed).

**Comment by Dyvinia** [comment]
did you link your frosty installation?

**Comment by Ooprec** [comment]
What do you mean by that?

**Comment by Dyvinia** [comment]
then you are using an outdated version of Frostyfix, update it

**Comment by Ooprec** [comment]
I am using version 4.2.0, which is the most recent version
