### ISSUE TITLE
FrostyFix cannot see Mod Profiles generated by FMM. Battlefront II (2017)

### ISSUE THREAD

**Issue by ToxeQ** [Dyvinia/FrostyFix#13]
I've had quite the hassle to even get the Frosty Mod Manager to generate mod profiles (Fun with registry editor), but the Fix can't see them and Battlefront 2 throws "The specified module could not be found" when launched. Followed by an Origin error (Invalid License Invalid Cipher Error Code = 0x0006). The game is installed on my system drive, formatted as NTFS. 

The Frosty Fix detects the game, but doesn't see the mod profiles and the game throws this error I mentioned. I selected my frosty mod manager install in the settings but that didin't help.

**Comment by Dyvinia** [comment]
can you send a screenshot of your moddata folder which is in your game directory?
