### ISSUE TITLE
Some tests on VirusTotal detects FrostyFix as malicious

### ISSUE THREAD

**Issue by Debrovski** [Dyvinia/FrostyFix#15]
Hello, comrade. I lead small, but active russian-speaking battlefront-lovers community. I often recommend FrostyFix, but people complain(or even blame) the tool for being "malicious". It would great to do something(if possible) about it.
![image](https://user-images.githubusercontent.com/30961903/155036064-89ebe631-acac-4271-8d1f-f424bb79c547.png)

**Comment by Dyvinia** [comment]
false positive, nothing i can do about that
