### ISSUE TITLE
FrostyFix not launching anymore

### ISSUE THREAD

**Issue by WolfXKills** [Dyvinia/FrostyFix#17]
The fix worked for me for a bit but now when I launch it doesn't seem to. Don't know if I'm not doing something right

**Comment by StarGazin17** [comment]
Yea bro me to, and no one here to fix it lol.

**Comment by StarGazin17** [comment]
Bro for now, go download frosty fix 4.2.1 that got my mods working again .

**Comment by Dyvinia** [comment]
use the latest version and provide the crash log
