### ISSUE TITLE
Frosty cant find thirdparty/unrar dll

### ISSUE THREAD

**Issue by HeavenlyAshura** [Dyvinia/FrostyFix#21]
im new to frosty and im trying to add some mods for star wars battlefront 2 but it cant find some dll or smth and after i click ok frosty crashes
![Bild_2022-06-09_034043606](https://user-images.githubusercontent.com/107160614/172746105-ec12e4a8-4ea2-446a-8f26-52c8b7578f0b.png)

**Comment by HeavenlyAshura** [comment]
found it out :/

**Comment by Dyvinia** [comment]
this is not an issue with frostyfix
