### ISSUE TITLE
Frosty doesnt display all games

### ISSUE THREAD

**Issue by IstAuchEgal** [Dyvinia/FrostyFix#22]
Want to launch BFV but it doesnt show up? Only thing that shows up for some reason is PvZ GW, also have multiple other BF games installed.
I've seen that on other issues the Author just said that "you didnt install the game properly" and closes the issue but you cant realy mess the installation up if you just download it on steam??

**Comment by Dyvinia** [comment]
You cannot even mod BFV with frosty in the first place

**Comment by IstAuchEgal** [comment]
> You cannot even mod BFV with frosty in the first place

Dont want to mod it, i heard it fixes an error i got - i never said i wanted to mod it
If its not supported add it to the list or create a list where you can see all compatible games

**Comment by Dyvinia** [comment]
This software is called **Frosty**Fix not GameFix
