### ISSUE TITLE
frosty fix crashing

### ISSUE THREAD

**Issue by Danielser214** [Dyvinia/FrostyFix#25]
hey my frostyfix crash averytime i start it. Can you help my ?

**Comment by Dyvinia** [comment]
i cannot do anything without a crash log and/or any additional information other than "it crashes"

**Comment by Danielser214** [comment]
it just say: no respond and than freeze.

**Comment by fortniteslay25** [comment]
same

**Comment by Dyvinia** [comment]
do you have net 6 desktop runtime installed?

**Comment by wyldcrd** [comment]
Attempt to run as administrator, turn it off and on again, and try a newer version.

**Comment by Dyvinia** [comment]
> Attempt to run as administrator, turn it off and on again, and try a newer version.

do you have net 6 desktop runtime installed?
