### ISSUE TITLE
Sorry if I'm being an idiot here, but I can't seem to get other packs to show up?

### ISSUE THREAD

**Issue by Imjusthereforhelp** [Dyvinia/FrostyFix#26]
So I'm using Frosty to try and make Mass Effect Andromeda a... More playable game, I need to test some mods, but when I make new packs in the manager (ver 1.0.6.0 BETA 4) they don't show up in Frosty Fix after multiple times reopening both programs, setting up my settings, bla bla bla, any idea why? Thanks for any help

**Comment by Dyvinia** [comment]
you have to launch the game with frosty once first
