### ISSUE TITLE
Frosty Fix doesn't display Dragon Age Inquisition

### ISSUE THREAD

**Issue by TheRealBananaMan76** [Dyvinia/FrostyFix#29]
So, I finally got this installed, got all the things I needed to get it running. However it won't detect Dragon Age Inquisition, which is installed through Steam, which should be impossible, considering I was playing it not long before I installed this and got it working.

However, it detects Mass Effect Andromeda, which is installed through Origin. I don't if there's any correlation between the fact that one is installed through origin and the other through steam, but I figured I'd give that info in case it's somehow relevant.

**Comment by Dyvinia** [comment]
if it doesnt show up, you can add it as a custom game in the settings window
