### ISSUE TITLE
it cant open

### ISSUE THREAD

**Issue by lleia11** [Dyvinia/FrostyFix#30]
Wywołanie konstruktora dla typu „FrostyFix4.MainWindow” zgodnego z określonymi ograniczeniami wiązania spowodowało wyjątek.

System.ComponentModel.Win32Exception (0x80004005): Odmowa dostępu
   w System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   w System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   w System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   w System.Diagnostics.Process.get_Handle()
   w Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   w Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   w FrostyFix4.MainWindow.CheckStatus()
   w FrostyFix4.MainWindow..ctor()

   w System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   w System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   w System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   w System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   w System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   w System.Windows.Application.DoStartup()
   w System.Windows.Application.<.ctor>b__1_0(Object unused)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dyvinia** [comment]
Run as Admin
