### ISSUE TITLE
error code and unsure of how to use the application

### ISSUE THREAD

**Issue by TheMuffinOwl** [Dyvinia/FrostyFix#32]
I have the steam version of pvz garden warfare 2. I try to apply the mods globally and launch the game but receive an error code.
 
Background thread has encountered an error and has been disabled:
Could not load file or assembly 'Gapotchenko.FX.Diagnostics.CommandLine, Version=2022.2.7.4096, Culture=neutral, PublicKeyToken=a750ee378eaf756f'. The system cannot find the file specified.

   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadArgumentList(Process process)
   at FrostyFix.MainWindow.GameStatusThread() in D:\Development\Visual Studio\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 186

**Comment by Dyvinia** [comment]
turn off the background thread option in settings

**Comment by Dyvinia** [comment]
fixed
