### ISSUE TITLE
FrostyFix cannot see Mod Profiles generated by FMM. Battlefront II (2017)

### ISSUE THREAD

**Issue by PetFinder2** [Dyvinia/FrostyFix#34]
I have 4.1 version of Frosty Fix i tried the newer ones they dont work either.

I simply Cannot see Mod Profiles so i cant select any ( should be showing "Default")

![image](https://user-images.githubusercontent.com/99842222/180337467-bead269a-be08-4699-b6ef-7e275cf33cb2.png)

Help would be very much appreciated.

**Comment by Dyvinia** [comment]
Launch the game through frosty once
