### ISSUE TITLE
Can't installed FrostyFix

### ISSUE THREAD

**Issue by extramuse** [Dyvinia/FrostyFix#36]
I try to installed FrostyFix, it's ask me to download NET framework.
I did it, installed it. 
But when i try again installed FrostyFix it's ask me the same think (download NET).
How can i fix this?

**Comment by extramuse** [comment]
Already found the answer

**Comment by ChefP00H** [comment]
> Already found the answer

What did you do to fix it because I have the same problem right now

**Comment by extramuse** [comment]
> > Already found the answer
> 
> What did you do to fix it because I have the same problem right now

I found answer here,  actually.  
https://github.com/Dyvinia/FrostyFix/issues/28
