### ISSUE TITLE
Frosty Fix wont open

### ISSUE THREAD

**Issue by creeperman17** [Dyvinia/FrostyFix#39]
Whenever I try to run FrostyFix.exe it poppes up a bar saying "To run this application, you must install missing frameworks for .NET. Would you like to download now?". When I click yes, nothing happens and the window just closes down. I have enabled both 3.5 NET frameworks  as well as the new 4.8 version and the same thing just keeps happening to me. I think this could be a problem with FrostyFix and I would be really happy if anyone helped me out on this one. 

There's also another guy here who has similar problems go check his comment.

**Comment by ChefP00H** [comment]
I had the EXACT SAME issue and fixed it by downloading frosty fix version 4.2.1 and then it worked. IF it doesn't open, run it as administrator (you'll have to do that every time but it's literally just the click of a button). Also to run it as Administrator, click the windows search bar, go on frosty fix, and it should give you the option of running it as administrator.

**Comment by Dyvinia** [comment]
you need .NET 6, not 3.5 or 4.8
