### ISSUE TITLE
Battlefront 2 Doesn't show up as a selectable game

### ISSUE THREAD

**Issue by DungYungus** [Dyvinia/FrostyFix#40]
I following a video's tutorial on how to install mods on BF2, however when I got to the fix section, I noticed that unlike others, BF2 doesn't pop up in fact it's blank. I tried to add it as a custom game, but it  just came up as an error. Any advice would be appreciated.

**Comment by wyldcrd** [comment]
Could you send the error?

**Comment by DungYungus** [comment]
It just comes up as STAR WARS Battlefront II Catastrophic failure.

**Comment by DungYungus** [comment]
Does it just not work for some computers?

**Comment by Dyvinia** [comment]
send an actual error log please
