### ISSUE TITLE
trying to install frostyfix but can't detect .net 6 runtime

### ISSUE THREAD

**Issue by setlec** [Dyvinia/FrostyFix#41]
So I've installed .net 6.0.0 (x64) runtime but frostyfix still can't detect it. I've uninstalled the 6.0.0 and installed vers 6.0.8 still nothing.

**Comment by asobod11138** [comment]
Same problem occure. I try to use latest version of FrostyFix(v5.2.0) and install .net(x64) 6.0.8, and also try .net 6.0.0 with uninstalling 6.0.8. For me, FrostyFix(v4.5.1) is works but all v5.x.x are not working.
