### ISSUE TITLE
I don't know what's going on. My battlefront 2 can't start after mod is installed. Mod manager only displays waiting for game

### ISSUE THREAD

**Issue by Reaper0525** [Dyvinia/FrostyFix#42]
This is the error code:
Background thread has encountered an error and has been disabled:
The given key 'GAME_DATA_DIR' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.Specialized.StringDictionaryWrapper.get_Item(String key)
   at FrostyFix.MainWindow.GameStatusThread() in D:\Development\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 189

**Comment by wyldcrd** [comment]
What platform do you own the game on?

**Comment by Reaper0525** [comment]
> 您在哪个平台上拥有游戏？

steam

**Comment by wyldcrd** [comment]
run frosty fix and select global and see if that works.

**Comment by wyldcrd** [comment]
If that doesn’t work, ping @Dyvinia and maybe ask in the battlefront 2 modding discord server.

**Comment by Dyvinia** [comment]
`Background thread has encountered an error and has been disabled:`
It disabled an extra feature and wont bother you anymore. not relevant to the main function of FrostyFix
