### ISSUE TITLE
i downloaded frosty fix 5.2 but i can't run it,

### ISSUE THREAD

**Issue by mochaofficial** [Dyvinia/FrostyFix#43]

**Comment by wyldcrd** [comment]
What file type is it displayed as @mochaofficial

**Comment by mochaofficial** [comment]
just exe ,when i runs it ,nothing happend,then i found some zip named "App crash_frosty fix.EXE"

**Comment by wyldcrd** [comment]
@Dyvinia does frostyfix put the crash logs in a zip file?

**Comment by mochaofficial** [comment]
yeah

**Comment by wyldcrd** [comment]
I was asking dyvinia, but could you unzip it and if it is a txt file can you post the crash report here

**Comment by mochaofficial** [comment]
no i can't ,it don't have "unzip" the option,i cant chage it into txt either

**Comment by mochaofficial** [comment]
<img width="999" alt="2022-09-28" src="https://user-images.githubusercontent.com/114421241/192699906-5aa9eb0b-3dda-41b5-ab75-127a74414ed4.png">

**Comment by mochaofficial** [comment]
> <img alt="2022-09-28" width="999" src="https://user-images.githubusercontent.com/114421241/192699906-5aa9eb0b-3dda-41b5-ab75-127a74414ed4.png">

sorry i accident close it . this is that crash file , i cant open it

**Comment by mochaofficial** [comment]
i cant upload that too

**Comment by mochaofficial** [comment]
sorry i accidently close this issue

**Comment by mochaofficial** [comment]
oh i chage it into a txt now
[Report.txt](https://github.com/Dyvinia/FrostyFix/files/9670768/Report.txt)

**Comment by mochaofficial** [comment]
hello?

**Comment by mochaofficial** [comment]
@Dyvinia @wyldcrd Hi guys？do you know what the problem is?
