### ISSUE TITLE
Game crashes after launching from EA Desktop.

### ISSUE THREAD

**Issue by Slddev** [Dyvinia/FrostyFix#45]
Trying to launch Star Wars: Battlefront 2 using FrostyFix from EA Desktop. When the play button is clicked in EA Desktop, the game crashes immediately with no window opening.

The game launches normally when EA Desktop is not launched from FrostyFix.

**Comment by ajk2113** [comment]
having the same issue with Dragon Age Inquisition

**Comment by Kenocrystal** [comment]
I have a similar issue where frosty fix doesn't work when setting it to EA desktop anymore, EA attempts to open the game, closes, then reopens like nothing happened, the game doesn't even launch when I apply the mods and then open EA myself. EA refuses to work until I disable the mod(s). I have to set it to globally and open the game manually (Plants Vs. Zombies GW2)

and its not even conflicting mod stuff, even with one mod enabled and nothing else

it used to work as intended when I first downloaded frosty fix, but now it doesn't

**Comment by Dyvinia** [comment]
Use dpfix instead
