### ISSUE TITLE
Frostyfix ruined my games!

### ISSUE THREAD

**Issue by LostManSVK** [Dyvinia/FrostyFix#47]
Frostyfix didn't find location of my game so I added custom and AND it didn't work btw and It broke my games, it won't launch anymore so I must reinstall... NEXT TIME MAKE FUNCTIONAL PROGRAM AND DON'T RELEASE NON-FUNCTIONAL PROGRAM UNTIL IT IS TESTED PERFECTLY!

**Comment by wyldcrd** [comment]
it is a functional program your problem is most likely user error 😐 anyway what game were you using and what is the problem

**Comment by Dyvinia** [comment]
@LostManSVK User error, reinstalling will change nothing

**Comment by wyldcrd** [comment]
Also to fix your issue you delete the moddata folder in the game folder and then you click disable mods in frostyfix (worked for me in battlefront 2)

**Comment by LostManSVK** [comment]
I SAID Frosty fix is not working, even games didn't find!

**Comment by wyldcrd** [comment]
🤦‍♂️ you need to install frosty mod manager first

**Comment by LostManSVK** [comment]
> 🤦‍♂️ you need to install frosty mod manager first, then install mods into your game by selecting start game. Then you open frostyfix.

You idiot I have already Frosty Mod Manager!
