### ISSUE TITLE
Frosty Fix does not launch game automatically

### ISSUE THREAD

**Issue by SeardnaSchmid** [Dyvinia/FrostyFix#49]
Hey there... first of all amazing work, thanks alot.

Bugreport:

Windows 10
Dragon Age Inquisition
EA Platform

- Using Frosty Mod Manager
- Applying all wanted mods
- Launch it one time to load apply mods
- Set up Frosty Fix
- Configure in Frosty Fix path to frosty mod manager
- launch via frosty fix
- ea starts up
- nothing happens...

- Maybe this is not a bug, but also in the readme there is described a different workflow.
- It workes if i then go into ea and start it through the launch button.

**Comment by Dyvinia** [comment]
just use dpfix instead
