### ISSUE TITLE
Game dosent start

### ISSUE THREAD

**Issue by Callimann8** [Dyvinia/FrostyFix#5]
So, first of all i use the ea Destop app with ea Play. When i press " Launch Game with Mods Enabled " Ea Destop start the game try to start and nothing happend. Did i do something wrong?
<img width="449" alt="ssssPNG" src="https://user-images.githubusercontent.com/64160770/139425804-f9b1f40a-8fab-4b0c-a474-f0ceee4522e2.PNG">

**Comment by Wawwior** [comment]
Same on Epic Games

**Comment by GabyNice345** [comment]
Has any of you found any fixes? i have the same problem

**Comment by trevorgunn** [comment]
I also couldn't get it to start with EA Desktop so I disabled that and enabled the Global option which did work for me.
