### ISSUE TITLE
.NET install required but I already have it

### ISSUE THREAD

**Issue by rom4ster** [Dyvinia/FrostyFix#50]
![image](https://user-images.githubusercontent.com/19560977/208850164-25d5d11c-9725-4fa6-affc-6906c099b1a0.png)

I have version 6.0.11 and 6.0.12, nothing works 

AND NO THIS IS NOT INVALID, THIS IS A REAL ISSUE SO DONT CLOSE IT, I already saw unresolved closed issues.

**Comment by Dyvinia** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.12-windows-x64-installer
