### ISSUE TITLE
Game visible in Task Manager > Details but not in Processes. Can't play.

### ISSUE THREAD

**Issue by Crygyn** [Dyvinia/FrostyFix#51]
Game: Dragon Age Inquisition

1. Latest release of the mod manager and FrostyFix as of today, Dec. 22, 2022. The same issue occurred earlier today and is what prompted the updating.
2. Both given admin permissions.
3. Game will run through normal EA Desktop and through FrostyModManager, both without mods.
4. FrostyFix seems to detect that I have Inquisition just fine.
4.1. It prompts to "select pack" on the right with only "ModData" available. Within DAI's folder there _is_ a folder called "ModData", but it is empty. Previously everything was working with mods stored in "FrostyModManager/Mods". There doesn't seem to be any insight as to what to do or expect with this feature so I'm mentioning here in case it's a potential weak spot in what I've done.
4.2. I hit launch, noting that in this case I do not get a "connecting to EA" window before it launches EA Desktop as with the other two options that _do_ run the game.
5. When I hit play either through FMM or the EA client the same things happens: It appears to work, the cursor gets a loading wheel, and then nothing happens. As mentioned in the title, if I go to the task manager > processes neither EA Desktop or DAI will be seen BUT if I go to the details tab I can find them both there taking up memory(but no CPU or GPU).
5.1 If I attempt to launch the game again with FMM I get an error claiming that game is already running under whatever Process ID. This is how I first found out that it was available in the "details" tab.

Edit:

6. If I end task on "EA Desktop.exe" and "EABackgroundService.exe" and then open the EA Desktop client I get the "connecting to EA" before it opens as expected, but _also_ I can hit play and it will run a second instance of DAI without issue. This one will show up in "Processes" under "Apps" as expected.
![image](https://user-images.githubusercontent.com/121273154/209268323-401f97da-2d8c-4217-84d3-0f6713492a47.png)
7. I also forgot to mention something. I noticed one issue people have might be caused by a file called "Bcrypt.dll". Neither my game nor FMM have that file, and FMM has something called "CryptBase.dll" in the same location I'd expect "Crypt.dll".

Everything worked fine two-three days ago, if that helps. Well, it started in windowed mode the last few times but I don't know if that's relevant.

Thanks,
Peter

**Comment by Dyvinia** [comment]
Does DatapathFix work https://github.com/Dyvinia/DatapathFixPlugin

**Comment by Crygyn** [comment]
Yes! That did it!

Thanks a million. For some reason, nothing to do with you at all I wouldn't think, clicking the link from the FrostyFix ReadMe didn't do anything last night. It works today.

Have a great day!
