### ISSUE TITLE
Stuck on black loading screen

### ISSUE THREAD

**Issue by graylion** [Dyvinia/FrostyFix#52]
- Latest versions of FrostyMod and FrostyFix as of today, 23/12/2022.
- Launch from EA without FrosrtyFix settings applied works, same for launch from FrostyModManager.
- Once I have run FrostyFix:
- - It does not launch through EA, when I click 'launch with mods enabled' in FrostyFix, it just opens the EA Desktop App
- - When I click 'Play' in EA, it loads to the main menu, when I click 'continue', it goes to the black loading screen with the throbbing DAI symbol in the bottom right and hangs there. It needs to be ended with Task Manager
- I have tried DataPathFixPlugin - no joy. Help!
- Many thanks in advance :)

**Comment by graylion** [comment]
Tried running FrostyFix with elevated permissions - same result

**Comment by wyldcrd** [comment]
What game are you using Frosty fix and frosty mod manager on?

**Comment by graylion** [comment]
apologies - DA:I

**Comment by graylion** [comment]
Solved - it was a
