### ISSUE TITLE
Games and profiles dont load even if i use administrator mode

### ISSUE THREAD

**Issue by knejfej** [Dyvinia/FrostyFix#6]
I have this problem profiles dont work and games i tried administrator mode but it didn't work
![image](https://user-images.githubusercontent.com/94729124/142713006-c86e19ff-608a-4a98-9ae2-1a8f05f109d8.png)

**Comment by BadBlackK** [comment]
I also have this problem

https://user-images.githubusercontent.com/96846326/147705432-f4cff1cd-a079-4099-a542-dceb03c6a929.mp4

**Comment by mg2000** [comment]
I have a also same problem.

**Comment by Dyvinia** [comment]
FrostyFix can't find your game, did you install them properly?

**Comment by riskybus** [comment]
> FrostyFix can't find your game, did you install them properly?

hey i have the same problem, trying to install mods to mirrors edge catalyst (downloaded it via xbox game pass) but games dont appear in the drop down menu

**Comment by mthoughtsswriter** [comment]
> hey i have the same problem, trying to install mods to mirrors edge catalyst but games dont appear in the drop down menu,
Same exact problem, except I have Catalyst on steam.
I could technically still use Origin but in order to play other Game Pass games I'm forced to download EA Play

**Comment by Dyvinia** [comment]
Mirror's Edge isnt supported by FF4 and iirc it does not work with the method that FF uses
